name = "TransducersBenchmarksReports"
uuid = "c444cbc0-a5b1-11e9-0278-1137774b98da"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
